import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Users, Home, GraduationCap, Heart } from "lucide-react";
import { NavLink } from "@/components/NavLink";

const DonationCategories = () => {
  const categories = [
    { title: "Support a Woman's Future", description: "Empower women through vocational training, entrepreneurship programs, and skill development initiatives that create sustainable livelihoods.", icon: <Users className="w-10 h-10" />, gradient: "from-primary to-primary/80", amount: "₹5,000" },
    { title: "Empower Rural Lives", description: "Transform rural communities with infrastructure development, agricultural training, and sustainable farming techniques for better living.", icon: <Home className="w-10 h-10" />, gradient: "from-accent to-accent/80", amount: "₹3,000" },
    { title: "Educate a Child", description: "Provide quality education, books, uniforms, and learning materials to underprivileged children for a brighter tomorrow.", icon: <GraduationCap className="w-10 h-10" />, gradient: "from-primary to-accent", amount: "₹2,000" },
    { title: "Give the Gift of Good Health", description: "Support health camps, medical checkups, and wellness programs that ensure healthy communities across all regions.", icon: <Heart className="w-10 h-10" />, gradient: "from-accent to-primary", amount: "₹4,000" },
  ];
  return <section className="py-16 md:py-24"><div className="container mx-auto px-4"><div className="text-center mb-12"><h2 className="text-3xl md:text-5xl font-bold text-foreground mb-4">Make a Difference Today</h2><p className="text-lg text-muted-foreground max-w-3xl mx-auto">Your contribution can transform lives. Choose a cause that resonates with your heart and create lasting impact.</p></div><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">{categories.map((category,index)=><Card key={index} className="group overflow-hidden border-2 hover:border-primary transition-all duration-300 hover:shadow-large"><CardContent className="p-6"><div className={`w-20 h-20 mx-auto mb-4 rounded-full bg-gradient-to-br ${category.gradient} flex items-center justify-center text-primary-foreground group-hover:scale-110 transition-transform duration-300 shadow-medium`}>{category.icon}</div><h3 className="text-xl font-bold text-foreground mb-3 text-center group-hover:text-primary transition-colors">{category.title}</h3><p className="text-sm text-muted-foreground mb-4 text-center leading-relaxed">{category.description}</p><div className="text-center mb-4"><p className="text-xs text-muted-foreground mb-1">Suggested Amount</p><p className="text-2xl font-bold text-primary">{category.amount}</p></div><NavLink to="/donate"><Button className={`w-full bg-gradient-to-br ${category.gradient} hover:opacity-90 transition-opacity shadow-medium text-primary-foreground`}>Donate Now</Button></NavLink></CardContent></Card>)}</div><div className="mt-12 text-center"><p className="text-muted-foreground mb-4">Want to contribute a different amount?</p><NavLink to="/donate"><Button size="lg" variant="outline" className="border-2 border-primary text-primary hover:bg-primary hover:text-primary-foreground">Choose Custom Amount</Button></NavLink></div></div></section>;
};
export default DonationCategories;
