import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";
import FloatingButtons from "@/components/FloatingButtons";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Calendar, User, ArrowRight, Tag } from "lucide-react";
import educationImage from "@/assets/program-education.jpg";
import communityImage from "@/assets/program-community.jpg";
import leadershipImage from "@/assets/program-leadership.jpg";

const Blog = () => {
  const posts = [
    { title: "Empowering Youth Through Education: Our 2024 Initiative", excerpt: "This year, we're launching an ambitious program to provide quality education to 10,000 more children across underserved communities...", image: educationImage, author: "Priya Sharma", date: "March 15, 2024", category: "Education", featured: true },
    { title: "The Power of Community-Led Development", excerpt: "Discover how grassroots initiatives are creating sustainable change in urban neighborhoods across the nation...", image: communityImage, author: "Rajesh Kumar", date: "March 10, 2024", category: "Community" },
    { title: "Leadership Development Success Stories", excerpt: "Meet the inspiring leaders who emerged from our programs and are now driving change in their communities...", image: leadershipImage, author: "Anita Patel", date: "March 5, 2024", category: "Leadership" },
    { title: "5 Ways You Can Make a Difference Today", excerpt: "Small actions can create big impacts. Here are practical ways you can start contributing to social change right now...", image: communityImage, author: "Vikram Singh", date: "February 28, 2024", category: "Impact" },
    { title: "Annual Impact Report 2023: A Year in Review", excerpt: "Looking back at our accomplishments, challenges, and the incredible impact we created together last year...", image: leadershipImage, author: "Priya Sharma", date: "February 20, 2024", category: "News" },
    { title: "Digital Literacy: Bridging the Technology Gap", excerpt: "How our digital education programs are helping communities access opportunities in the digital age...", image: educationImage, author: "Rajesh Kumar", date: "February 15, 2024", category: "Education" },
  ];
  const featuredPost = posts.find((p) => p.featured);
  const regularPosts = posts.filter((p) => !p.featured);
  return (
    <div className="min-h-screen">
      <Navigation />
      <section className="pt-32 pb-16 md:pb-24 bg-gradient-primary"><div className="container mx-auto px-4 text-center"><h1 className="text-4xl md:text-6xl font-bold mb-6 text-primary-foreground animate-fade-in">Blog & News</h1><p className="text-lg md:text-xl text-primary-foreground/90 max-w-3xl mx-auto animate-slide-up">Stories, updates, and insights from the field of social impact.</p></div></section>
      {featuredPost && <section className="py-16 md:py-24"><div className="container mx-auto px-4"><Card className="max-w-5xl mx-auto overflow-hidden border-2 border-primary shadow-large animate-scale-in"><div className="grid grid-cols-1 md:grid-cols-2 gap-0"><div className="relative h-64 md:h-auto"><img src={featuredPost.image} alt={featuredPost.title} className="w-full h-full object-cover" /><div className="absolute top-4 left-4 px-3 py-1 bg-accent text-accent-foreground text-sm font-bold rounded-full">Featured</div></div><CardContent className="p-8 flex flex-col justify-center"><div className="flex items-center gap-2 text-sm text-primary font-medium mb-3"><Tag className="w-4 h-4" /><span>{featuredPost.category}</span></div><h2 className="text-2xl md:text-3xl font-bold mb-4 text-foreground">{featuredPost.title}</h2><p className="text-muted-foreground mb-4 leading-relaxed">{featuredPost.excerpt}</p><div className="flex items-center gap-4 text-sm text-muted-foreground mb-6"><div className="flex items-center gap-1"><User className="w-4 h-4" /><span>{featuredPost.author}</span></div><div className="flex items-center gap-1"><Calendar className="w-4 h-4" /><span>{featuredPost.date}</span></div></div><Button className="bg-gradient-accent hover:opacity-90 transition-opacity group self-start">Read Full Story<ArrowRight className="ml-2 w-4 h-4 group-hover:translate-x-1 transition-transform" /></Button></CardContent></div></Card></div></section>}
      <section className="py-16 md:py-24 bg-secondary/30"><div className="container mx-auto px-4"><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">{regularPosts.map((post, index) => <Card key={index} className="group overflow-hidden border-2 hover:border-primary transition-all duration-300 hover:shadow-large animate-scale-in" style={{ animationDelay: `${index * 100}ms` }}><div className="relative h-48 overflow-hidden"><img src={post.image} alt={post.title} className="w-full h-full object-cover group-hover:scale-110 transition-transform duration-500" /><div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent" /><div className="absolute top-4 left-4 px-3 py-1 bg-primary/90 text-primary-foreground text-xs font-medium rounded-full">{post.category}</div></div><CardContent className="p-6"><h3 className="text-lg font-bold mb-3 text-foreground group-hover:text-primary transition-colors line-clamp-2">{post.title}</h3><p className="text-sm text-muted-foreground mb-4 line-clamp-3">{post.excerpt}</p><div className="flex items-center gap-3 text-xs text-muted-foreground mb-4"><div className="flex items-center gap-1"><User className="w-3 h-3" /><span>{post.author}</span></div><div className="flex items-center gap-1"><Calendar className="w-3 h-3" /><span>{post.date}</span></div></div><Button variant="ghost" className="p-0 h-auto text-primary hover:text-primary/80 group/btn">Read More<ArrowRight className="ml-2 w-4 h-4 group-hover/btn:translate-x-1 transition-transform" /></Button></CardContent></Card>)}</div></div></section>
      <section className="py-16 md:py-24"><div className="container mx-auto px-4"><Card className="max-w-3xl mx-auto text-center bg-gradient-hero text-primary-foreground border-0 shadow-large"><CardContent className="p-8 md:p-12"><h2 className="text-3xl font-bold mb-4">Stay Updated</h2><p className="text-lg mb-6 opacity-90">Subscribe to our newsletter for the latest stories, updates, and opportunities to get involved.</p><div className="flex flex-col sm:flex-row gap-3 max-w-md mx-auto"><input type="email" placeholder="Your email address" className="flex-1 px-4 py-3 rounded-lg bg-background/20 backdrop-blur-sm border border-primary-foreground/30 text-primary-foreground placeholder:text-primary-foreground/60 focus:outline-none focus:ring-2 focus:ring-primary-foreground" /><Button className="bg-background text-foreground hover:bg-background/90">Subscribe</Button></div></CardContent></Card></div></section>
      <FloatingButtons /><Footer />
    </div>
  );
};
export default Blog;
