import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";
import FloatingButtons from "@/components/FloatingButtons";
import HeroCarousel from "@/components/HeroCarousel";
import ImpactCounter from "@/components/ImpactCounter";
import ProgramSections from "@/components/ProgramSections";
import GalleryCarousel from "@/components/GalleryCarousel";
import NewsUpdatesWidget from "@/components/NewsUpdatesWidget";
import DonationCategories from "@/components/DonationCategories";
import QuickLinksSection from "@/components/QuickLinksSection";
import { Button } from "@/components/ui/button";
import { NavLink } from "@/components/NavLink";
import { Heart, ArrowRight, Users, Star } from "lucide-react";

const Index = () => (
  <div className="min-h-screen">
    <Navigation />
    <HeroCarousel />
    <section className="py-12 bg-card border-y border-border"><div className="container mx-auto px-4"><ImpactCounter /></div></section>
    <section className="py-10 bg-secondary/30"><div className="container mx-auto px-4"><QuickLinksSection /></div></section>
    <section className="py-16 md:py-24"><div className="container mx-auto px-4"><div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center"><div className="animate-fade-in"><span className="inline-block text-sm font-semibold text-primary uppercase tracking-widest mb-3">Who We Are</span><h2 className="text-3xl md:text-5xl font-bold text-foreground mb-6 leading-tight">A Movement Built on <span className="text-primary">Compassion</span></h2><p className="text-muted-foreground text-lg mb-5 leading-relaxed">Divy Shrishti is a registered NGO working since 2015 to uplift marginalized communities through education, health care, women empowerment, and environmental sustainability.</p><p className="text-muted-foreground text-base mb-8 leading-relaxed">With a dedicated team of over 500 volunteers and strong community partnerships, we deliver impactful programs that change lives and build futures.</p><div className="flex flex-col sm:flex-row gap-4"><NavLink to="/about"><Button className="bg-gradient-primary hover:opacity-90 text-primary-foreground gap-2">Our Story <ArrowRight className="w-4 h-4" /></Button></NavLink><NavLink to="/get-involved"><Button variant="outline" className="gap-2 border-primary text-primary hover:bg-primary hover:text-primary-foreground"><Users className="w-4 h-4" /> Volunteer With Us</Button></NavLink></div></div><div className="relative"><div className="rounded-2xl overflow-hidden shadow-large"><img src="/src/assets/hero-volunteers.jpg" alt="Divy Shrishti volunteers" className="w-full h-96 object-cover" /></div><div className="absolute -bottom-6 -left-6 bg-background rounded-xl shadow-large border border-border p-4 flex items-center gap-3"><div className="w-12 h-12 rounded-full bg-gradient-primary flex items-center justify-center text-primary-foreground"><Star className="w-5 h-5" /></div><div><p className="font-bold text-foreground text-xl">10+ Years</p><p className="text-muted-foreground text-sm">Of Community Service</p></div></div></div></div></div></section>
    <section className="py-16 md:py-24 bg-secondary/20"><div className="container mx-auto px-4"><div className="text-center mb-12"><span className="inline-block text-sm font-semibold text-primary uppercase tracking-widest mb-3">What We Do</span><h2 className="text-3xl md:text-5xl font-bold text-foreground mb-4">Our Core Programs</h2><p className="text-muted-foreground text-lg max-w-2xl mx-auto">Comprehensive initiatives designed to create lasting, measurable change across communities.</p></div><ProgramSections /><div className="text-center mt-10"><NavLink to="/programs"><Button variant="outline" className="border-primary text-primary hover:bg-primary hover:text-primary-foreground gap-2">View All Programs <ArrowRight className="w-4 h-4" /></Button></NavLink></div></div></section>
    <section className="py-16 md:py-20"><div className="container mx-auto px-4"><div className="text-center mb-10"><span className="inline-block text-sm font-semibold text-primary uppercase tracking-widest mb-3">Gallery</span><h2 className="text-3xl md:text-4xl font-bold text-foreground">Our Work in Action</h2></div><GalleryCarousel /></div></section>
    <section className="py-16 bg-gradient-hero text-primary-foreground"><div className="container mx-auto px-4 text-center"><h2 className="text-3xl md:text-5xl font-bold mb-5">Your Support Changes Lives</h2><p className="text-primary-foreground/85 text-lg md:text-xl mb-8 max-w-2xl mx-auto">Even a small contribution can help a child get an education, a family get health care, or a community rebuild.</p><div className="flex flex-col sm:flex-row gap-4 justify-center"><NavLink to="/donate"><Button size="lg" className="bg-background text-foreground hover:bg-background/90 gap-2 shadow-large px-8"><Heart className="w-5 h-5 text-red-500 fill-red-500" />Donate Today</Button></NavLink><NavLink to="/get-involved"><Button size="lg" variant="outline" className="border-primary-foreground text-primary-foreground hover:bg-primary-foreground hover:text-primary px-8">Volunteer With Us</Button></NavLink></div></div></section>
    <section className="py-16 md:py-20"><div className="container mx-auto px-4"><div className="text-center mb-10"><span className="inline-block text-sm font-semibold text-primary uppercase tracking-widest mb-3">Ways to Give</span><h2 className="text-3xl md:text-4xl font-bold text-foreground mb-4">Choose Your Impact</h2><p className="text-muted-foreground text-lg max-w-xl mx-auto">Every rupee goes directly to our programs.</p></div><DonationCategories /></div></section>
    <section className="py-16 bg-secondary/20"><div className="container mx-auto px-4"><div className="text-center mb-10"><span className="inline-block text-sm font-semibold text-primary uppercase tracking-widest mb-3">Latest</span><h2 className="text-3xl md:text-4xl font-bold text-foreground">News & Updates</h2></div><NewsUpdatesWidget /><div className="text-center mt-8"><NavLink to="/blog"><Button variant="outline" className="border-primary text-primary hover:bg-primary hover:text-primary-foreground gap-2">Read All Articles <ArrowRight className="w-4 h-4" /></Button></NavLink></div></div></section>
    <FloatingButtons /><Footer />
  </div>
);
export default Index;
