import axios, { AxiosInstance } from 'axios';

const baseURL = import.meta.env.VITE_API_URL || '/api';
const api: AxiosInstance = axios.create({ baseURL: baseURL.replace(/\/$/, ''), withCredentials: true, headers: { 'Content-Type': 'application/json' } });

api.interceptors.response.use((response) => response, (error) => Promise.reject(error));

export const authAPI = {
    login: (email: string, password: string) => api.post('/auth/login', { email, password }),
    register: (data: any) => api.post('/auth/register', data),
    logout: () => api.post('/auth/logout'),
    getCurrentUser: () => api.get('/auth/me')
};

export const membershipAPI = { register: (data: any) => api.post('/admin/memberships', data), getMemberships: () => api.get('/admin/memberships'), getMembershipById: (id: string) => api.get(`/memberships/${id}`), renewMembership: (id: string) => api.post(`/memberships/${id}/renew`), suspendMembership: (id: string) => api.post(`/admin/memberships/${id}/suspend`) };
export const donationAPI = { getDonations: () => api.get('/admin/donations'), createDonation: (data: any) => api.post('/donations', data), createOrder: (data: any) => api.post('/donations/order', data), verifyPayment: (data: any) => api.post('/donations/verify', data), getUserDonations: () => api.get('/donations/user/history'), getStats: () => api.get('/admin/donations/stats'), updateStatus: (id: string, status: string) => api.patch(`/admin/donations/${id}/status`, { status }) };
export const certificateAPI = { getCertificates: () => api.get('/admin/certificates'), getVisitorCertificates: () => api.get('/admin/certificates?type=visitor'), verifyCertificate: (code: string) => api.get(`/certificates/verify/${encodeURIComponent(code)}`), issueCertificate: (data: any) => api.post('/admin/certificates', data), issueVisitorCertificate: (data: any) => api.post('/admin/certificates/visitor', data) };
export const newsAPI = { getAllNews: () => api.get('/news'), getNewsBySlug: (slug: string) => api.get(`/news/${encodeURIComponent(slug)}`), getAdminNews: () => api.get('/admin/news'), createNews: (data: any) => api.post('/admin/news', data), updateNews: (id: string, data: any) => api.put(`/admin/news/${id}`, data), publishNews: (id: string) => api.post(`/admin/news/${id}/publish`), deleteNews: (id: string) => api.delete(`/admin/news/${id}`) };
export const activityAPI = { getActivities: () => api.get('/activities'), getActivityById: (id: string) => api.get(`/activities/${id}`), createActivity: (data: any) => api.post('/admin/activities', data), likeActivity: (id: string) => api.post(`/activities/${id}/like`), commentOnActivity: (id: string, comment: string) => api.post(`/activities/${id}/comment`, { comment }), deleteActivity: (id: string) => api.delete(`/admin/activities/${id}`) };
export const campaignAPI = { getCampaigns: () => api.get('/campaigns'), getCampaignById: (id: string) => api.get(`/campaigns/${id}`), getActiveCampaigns: () => api.get('/campaigns/active'), createCampaign: (data: any) => api.post('/admin/campaigns', data), updateCampaign: (id: string, data: any) => api.put(`/admin/campaigns/${id}`, data), closeCampaign: (id: string) => api.post(`/admin/campaigns/${id}/close`), donateToCampaign: (id: string, amount: number) => api.post(`/campaigns/${id}/donate`, { amount }) };
export const projectAPI = { getProjects: () => api.get('/projects'), getProjectById: (id: string) => api.get(`/projects/${id}`), createProject: (data: any) => api.post('/admin/projects', data), recordExpense: (projectId: string, data: any) => api.post(`/admin/projects/${projectId}/expenses`, data), getProjectReports: (id: string) => api.get(`/projects/${id}/reports`) };
export const beneficiaryAPI = { getBeneficiaries: () => api.get('/admin/beneficiaries'), getBeneficiaryById: (id: string) => api.get(`/admin/beneficiaries/${id}`), addBeneficiary: (data: any) => api.post('/admin/beneficiaries', data), updateBeneficiary: (id: string, data: any) => api.put(`/admin/beneficiaries/${id}`, data), searchBeneficiaries: (query: string) => api.get(`/admin/beneficiaries/search?q=${encodeURIComponent(query)}`), addHelpHistory: (id: string, data: any) => api.post(`/admin/beneficiaries/${id}/help-history`, data) };
export const eventAPI = { getEvents: () => api.get('/events'), getEventById: (id: string) => api.get(`/events/${id}`), getUpcomingEvents: () => api.get('/events/upcoming'), createEvent: (data: any) => api.post('/admin/events', data), registerForEvent: (id: string) => api.post(`/events/${id}/register`) };
export const internshipAPI = { getInternships: () => api.get('/internships'), getInternshipById: (id: string) => api.get(`/internships/${id}`), createInternship: (data: any) => api.post('/admin/internships', data), applyForInternship: (id: string) => api.post(`/internships/${id}/apply`) };
export const enquiryAPI = { submitEnquiry: (data: any) => api.post('/enquiries', data), getEnquiries: () => api.get('/admin/enquiries'), getEnquiryById: (id: string) => api.get(`/admin/enquiries/${id}`), replyToEnquiry: (id: string, reply: string) => api.post(`/admin/enquiries/${id}/reply`, { reply }), markAsRead: (id: string) => api.patch(`/admin/enquiries/${id}`, { status: 'read' }), deleteEnquiry: (id: string) => api.delete(`/admin/enquiries/${id}`) };
export const messageAPI = { getMessages: () => api.get('/admin/messages'), getMessageById: (id: string) => api.get(`/admin/messages/${id}`), sendMessage: (data: any) => api.post('/admin/messages', data), scheduleMessage: (data: any) => api.post('/admin/messages/schedule', data), deleteMessage: (id: string) => api.delete(`/admin/messages/${id}`) };
export const receiptAPI = { getReceipts: () => api.get('/admin/receipts'), getUserReceipts: () => api.get('/receipts/user'), getReceiptsByType: (type: string) => api.get(`/admin/receipts?type=${encodeURIComponent(type)}`), createReceipt: (data: any) => api.post('/admin/receipts', data), voidReceipt: (id: string) => api.post(`/admin/receipts/${id}/void`) };
export const volunteerAPI = { getVolunteers: () => api.get('/admin/volunteers'), register: (data: any) => api.post('/admin/volunteers', data), updateStatus: (id: string, status: string) => api.patch(`/admin/volunteers/${id}/status`, { status }), updateHours: (id: string, hours: number) => api.patch(`/admin/volunteers/${id}/hours`, { hours }), verifyBackground: (id: string, verified: boolean) => api.patch(`/admin/volunteers/${id}/background`, { verified }), assignTask: (id: string, taskId: string) => api.post(`/admin/volunteers/${id}/tasks`, { taskId }), delete: (id: string) => api.delete(`/admin/volunteers/${id}`) };
export const reportAPI = { generateMembershipReport: () => api.get('/admin/reports/membership', { responseType: 'blob' }), generateDonationReport: () => api.get('/admin/reports/donations', { responseType: 'blob' }), generateProjectReport: () => api.get('/admin/reports/projects', { responseType: 'blob' }), generateBeneficiaryReport: () => api.get('/admin/reports/beneficiaries', { responseType: 'blob' }), generateExpenseReport: () => api.get('/admin/reports/expenses', { responseType: 'blob' }), generateIncomeVsExpenseReport: () => api.get('/admin/reports/income-expense', { responseType: 'blob' }) };

export default api;
